export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const SET_CATEGORY = 'SET_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export default {
  SET_CATEGORY_LIST,
  SET_CATEGORY,
  UPDATE_CATEGORY,
  DELETE_CATEGORY
}
