export const SET_POST_LIST = 'SET_POST_LIST';
export const SET_MY_POST_LIST = 'SET_MY_POST_LIST';
export const SET_POST = 'SET_POST';
export const SET_CATEGORY = 'SET_CATEGORY';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_MY_POST = 'DELETE_MY_POST';

export default {
  SET_POST_LIST,
  SET_MY_POST_LIST,
  SET_POST,
  SET_CATEGORY,
  UPDATE_POST,
  DELETE_POST,
  DELETE_MY_POST,
}
